#! /bin/bash
#$ -S /bin/bash
#$ -N 'q0_chrna3'
#$ -cwd
#$ -pe smp 3
#$ -wd  /emc/cbmr/users/zlc436/smoking_project/info_4_loci/3_intermediary_input_files/qsub_files
conda activate r_env
Rscript /emc/cbmr/kilpelainen/tools/auto_locus_zoom/code/internal/0_setting_up_temporal_data.R /emc/cbmr/users/zlc436/smoking_project/info_4_loci/2_input_commands/chrna3.cfg
