#! /bin/bash
#$ -S /bin/bash
#$ -N 'q0_15_78896129_coloc_with_bigger_N_4_whradjbmi'
#$ -cwd
#$ -pe smp 3
#$ -wd  /emc/cbmr/users/zlc436/smoking_project/CODE/1_locus_zoom/2_locus_zoom/2_intermediary_code_and_files/qsub_files
conda activate r_env
Rscript /emc/cbmr/kilpelainen/tools/auto_locus_zoom/code/internal/0_setting_up_temporal_data.R /emc/cbmr/users/zlc436/smoking_project/CODE/1_locus_zoom/2_locus_zoom/1_input_and_code/cortisol_coloc.cfg
