#! /bin/bash
#$ -S /bin/bash
#$ -N 'q1_15_78896129_coloc_with_bigger_N_4_whradjbmi'
#$ -hold_jid 'q0_15_78896129_coloc_with_bigger_N_4_whradjbmi'
#$ -cwd
#$ -pe smp 3
#$ -l h_vmem=6G
#$ -l s_vmem=4G
#$ -wd  /emc/cbmr/users/zlc436/smoking_project/CODE/1_locus_zoom/2_locus_zoom/2_intermediary_code_and_files/qsub_files
conda activate r_env
bash /emc/cbmr/kilpelainen/tools/auto_locus_zoom/code/internal/1_loop_extracting_data_from_loci
